### ISSUE TITLE
[FEATURE REQUEST] kanban boards into emacs?

### ISSUE THREAD

**Issue by vanangamudi** [magit/ghub#107]
is there any plan to integrate github projects and kanban boards into ghub?

I apologize for the ugly tag [FEATURE REQUEST]

**Comment by tarsius** [comment]
I don't plan to add support for "projects" to [`forge`](https://github.com/magit/forge) any time soon. Until I do that I also don't intend to change `ghub-fetch-repository` to fetch the respective data. However it shouldn't be too hard to adjust that for your own use, except that it involves looking at the graphql api documentation.

Of course implementing an actual kanban board application in Emacs is a whole other story than just fetching the data. There are at least two packages that do that but I don't know whether the can be synchronized with github.

* https://hg.sr.ht/~arnebab/kanban.el
* hps://github.com/gizmomogwai/org-kanban
