### ISSUE TITLE
Importance of username case for API authinfo retrieval

### ISSUE THREAD

**Issue by Zaeph** [magit/ghub#111]
Hello,

I've finally been able to identify why `ghub` could generate an API key from GitHub.  It has to do with the case of your user-name.

My `user-login-name` is `zaeph`, whilst my username on GitHub is `Zaeph`.  It turns out that `ghub`'s match for your username is case-sensitive.  For some reason, `ghub` wasn't writing to my `authinfo.gpg` file, which led me to do it manually.  In my hubris, I'd written the following:
```
machine api.github.com login Zaeph^forge password [REDACTED]
```

My reasoning was that the username was only used to identify yourself on GitHub's server, *not* to also help `ghub` match your API-key.

Also, I assume that the only reason it worked on GitHub's end was that `zaeph` and `Zaeph` both resolve to the same user-name.  It might not be the case for other forges.

Could we maybe mention this in the `yes-or-no-p` query-string in `ghub--confirm-create-token`?  Since we're already warning about the use of a non-encrypted `authinfo`, we might as well warn users to pay attention to the case of their user-name.

**Comment by tarsius** [comment]
Thanks for the suggestion but I feel that this additional hint would be irrelevant to the vast majority of users and as such would be a distraction from the other hints they should pay attention to.

**Comment by Zaeph** [comment]
Could we settle for a footnote in the wiki?

**Comment by tarsius** [comment]
Yes. (Probably not a footnote but a proper paragraph.)

Would you mind writing something?

**Comment by Zaeph** [comment]
> Yes. (Probably not a footnote but a proper paragraph.)
> 
> Would you mind writing something?

Already on it.  Figuring out the `Makefile` now.

How do you like this:
```
If you store the token in a file like @code{~/.authinfo}, then note that
@code{auth-source}'s parsing of that file is brittle.  Make sure the
file ends with a newline character, that your user-name has the right     <---
case, that there are no empty or invalid lines, and that all comments are
prefixed with @code{#}.
```

**Comment by Zaeph** [comment]
Ah, actually, it's still ambiguous.  I'll write a proper paragraph.
