### ISSUE TITLE
Dead link to Gitlab Tokens in documentation

### ISSUE THREAD

**Issue by artpelling** [magit/ghub#147]
Came here to report a dead link. Just noticed that it has been fixed in 865424d4faf66048bfb3752856ac0cf68e1c6efe

However, the correct link is not shown on the docs website:
https://magit.vc/manual/ghub/Creating-a-Token.html#Creating-a-Token

**Comment by tarsius** [comment]
I've published the latest version now. Thanks for letting me know.
