### ISSUE TITLE
Expose response headers

### ISSUE THREAD

**Issue by vermiculus** [magit/ghub#16]
There are lots of neat things that could be done by paying attention to response headers:
* https://developer.github.com/v3/#rate-limiting
* https://developer.github.com/v3/#conditional-requests

I don't expect `ghub` to handle these (after all, it's the *miniscule* GitHub client), but it wouldn't be crazy for `ghub+` to handle them smartly *if* they were made available.

Since we want to keep the main JSON response as simple as possible to use, it would probably be best to use something like this:

```
(defvar ghub-response-headers nil
  "An alist of response headers from the last request.
When a method is called, this variable is reset to be an alist of
the headers for that method.

For example, you should expect to see at least the following
headers after calling \(ghub-get \"/meta\"\):

    \(\(request . \"/meta\"\)
     \(method . \"GET\"\)
     \(\"Status\" . \"200 OK\"\)
     \(\"X-RateLimit-Limit\" . \"60\"\)
     \(\"X-RateLimit-Remaining\" . \"58\"\)
     \(\"X-RateLimit-Reset\" . \"1495154422\"\)\)")
```

**Comment by vermiculus** [comment]
Actually, conditional requests should already be handled if `url-automatic-caching` is t. See my emacs SE question on that.

**Comment by tarsius** [comment]
> Actually, conditional requests should already be handled if `url-automatic-caching` is t.

So I don't have to do anything? Or should that variable be bound in `ghub--request`?

> See my emacs SE question on that. 

Link?

**Comment by vermiculus** [comment]
It should be bound in `ghub--request`.

It looks like I was on mobile when I did all this; here's [the Emacs.SE question](https://emacs.stackexchange.com/a/32952/2264).

**Comment by tarsius** [comment]
Please also post a link to the debbug issue.

**Comment by tarsius** [comment]
Could you please open a PR?

**Comment by vermiculus** [comment]
> Could you please open a PR?

Given that I still can't get it to work, a PR would be premature (and empty). I'll see if I can give this some attention tonight.

**Comment by tarsius** [comment]
This appears fairly simple to do. See https://github.com/tarsius/ghub/compare/store-response-headers?expand=1.

**Comment by tarsius** [comment]
Does 7f00258c09f439d52c9547cc243647afb650e780 (on `master` now) work for you?

**Comment by vermiculus** [comment]
I shall test tonight.

**Comment by vermiculus** [comment]
It works fantastically, thank you!
