### ISSUE TITLE
Does treepy go up to 0.1.2?

### ISSUE THREAD

**Issue by dickmao** [magit/ghub#160]
In 05753f8, treepy gets bumped to 0.1.2, and as near as I can tell it only goes up to 0.1.1.

**Comment by cryptorick** [comment]
> In [05753f8](https://github.com/magit/ghub/commit/05753f872a7450bff7b0f83aec9e26eee9d9f84c), treepy gets bumped to 0.1.2, and as near as I can tell it only goes up to 0.1.1.

What he said.

**Comment by cryptorick** [comment]
@tarsius I'm trying to see if Daniel will bump the version instead: https://github.com/volrath/treepy.el/pull/12
