### ISSUE TITLE
ghub--token: Required Github token does not exist

### ISSUE THREAD

**Issue by mrcnski** [magit/ghub#161]
Hi, sorry to pollute your pristine issue tracker. I was bumping my head against this for a while...

```
auth-source-search: found 3 backends matching (:host "api.github.com" :user "mrcnski^forge" :max 1)
auth-source-search-backend: got 1 (max 1) in netrc:~/.authinfo matching (:host "api.github.com" :user "mrcnski^forge" :max 1)
auth-source-search: found 1 results (max 1) matching (:host "api.github.com" :user "mrcnski^forge" :max 1)
ghub--token: Required Github token ("mrcnski^forge" for "api.github.com") does not exist.
```

As you can see the log is not very helpful! Then I found out, that in `.authinfo` I had replaced `password` with my token, instead of leaving `password` there. 🤦‍♂️

I wonder if it's possible to emit a better error in this case, or at least make it more clear in the manual?

Thank you. 🙏

**Comment by tarsius** [comment]
> I wonder if it's possible to emit a better error in this case,

I don't think so. There already is a lot of code in place to detect potential user mistakes. That code comes at a price too, e.g., it might itself contain bugs.

> or at least make it more clear in the manual?

It is very hard to strike a balance in the ghub and forge manuals between mentioning every mistake a user might make and providing a simple step by step guide to get things going. If there are too many details, then users just skim it and thus shoot themselves in the food even though there actually was a warning about exactly the mistake they made. If too few details are provided, then I get asked to add more instead. There have already been a few rounds of asking me in turn for either a simple tutorial or then again for a text mentioning each and every detail, and I think I am just going to leave things as they are.

But I have added a note to https://github.com/magit/forge/wiki/Common-mistakes.

**Comment by mrcnski** [comment]
Understood, thanks for doing what you can. Very much appreciated!
