### ISSUE TITLE
ghub--token is broken, can't find my token

### ISSUE THREAD

**Issue by DarwinAwardWinner** [magit/ghub#24]
`ghub--token` uses `auth-source-search` to search for the Github token. I put my token in `~/.netrc`, but it still can't find it. The reason seems to be that the order of keywords passed to `auth-source-search` is significant. `(auth-source-search :max 1 :user "DarwinAwardWinner" :host "api.github.com")` returns nil, while `(auth-source-search :user "DarwinAwardWinner" :host "api.github.com" :max 1)` returns my Github login. `ghub--token` uses the former. I notice that all the examples in the docstring for `auth-source-search` put `:max 1` at the end of the search specification, but the docstring doesn't appear to document this order-dependence, so I'm not sure if it's a bug or a feature.

**Comment by tarsius** [comment]
Sounds like a bug to me. Anyway, I want to reproduce it before I work around it. What Emacs version is that?

**Comment by DarwinAwardWinner** [comment]
GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21

**Comment by tarsius** [comment]
Can you reproduce it when using `~/.authinfo` or `~/authinfo.gpg`?

**Comment by DarwinAwardWinner** [comment]
Actually, I finally tracked down the cause: auth-source seems to be caching nil results. So in the very common case of auth-source looking for a missing entry and then telling the user to add the entry, it won't pick up the new entry unless you run `(auth-source-forget+)` first.

**Comment by DarwinAwardWinner** [comment]
Also, I have no idea why changing the order of the arguments affects whether or not it hits the cache.

**Comment by tarsius** [comment]
Cache invalidation is implemented in the `pu` branch. Closing this issue in favor of #25.
