### ISSUE TITLE
Setting up multiple github accounts

### ISSUE THREAD

**Issue by shivanth** [magit/ghub#26]
I see `git config --global github.user <username>` in the documentation to setup ghub. Can I not use local configuration because I've multiple github accounts?

**Comment by vermiculus** [comment]
Have you tried using local configuration? I don't think there's anything in the code that looks specifically to global config – it's just easier for most folks who would only have one account.

**Comment by shivanth** [comment]
Documentation could be clearer 😄 .

**Comment by tarsius** [comment]
Yes, I will add better documentation as part of my work on #25.
