### ISSUE TITLE
error message about authentication is uninformative

### ISSUE THREAD

**Issue by kleinschmidt** [magit/ghub#29]
As far as I've experienced, there's just a single, generic message about authentication failing.  It would be helpful in debugging authentication problems if there's a more informative error message.  For instance, I made a mistake and called my file `~/authinfo.gpg` instead of `~/.authinfo.gpg`.  If the error message had said that the auth file couldn't be found that would have made chasing this down much easier.

**Comment by alphapapa** [comment]
Another possible problem is that Emacs has cached out-of-date or non-existent authinfo data.  I had to run `auth-source-forget-all-cached`, and then suddenly it worked.  It would be good if this were mentioned in "Initial configuration" in the readme.

**Comment by tarsius** [comment]
> Another possible problem is that Emacs has cached out-of-date or non-existent authinfo data.

The upcoming v2 deals with this.

> As far as I've experienced, there's just a single, generic message about authentication failing.

v2 also comes with more useful errors in some cases - or it even helps the user to complete the configuration. Some errors are beyond `ghub`'s control though (i.e. when `auth-sources` is having an issue.

I am closing this. If after I have released v2 you still get uninformative error messages, then please mention it here and we can deal with it then.
