### ISSUE TITLE
URL buffers are left hanging around

### ISSUE THREAD

**Issue by vermiculus** [magit/ghub#30]
`url.el` obviously doesn't kill buffers retrieved. During a longer session, this ends up in many, many buffers just hanging around in memory. We should probably kill them.

Some of these buffers contain sensitive information, so it would definitely be good to kill them off when we're done. It might not be a perfect solution, but it would minimize the hole. (See value of `(buffer-local-variables *buf*)` on a buffer generated by url.el via ghub.)

**Comment by vermiculus** [comment]
As a stopgap for those concerned, the following will kill all url buffers:
```elisp
(-map #'kill-buffer
      (--filter
       (alist-get 'url-http-method (buffer-local-variables it))
       (buffer-list)))
```

**Comment by tarsius** [comment]
Coming soon in v2 :wink:
