### ISSUE TITLE
Suggest scopes

### ISSUE THREAD

**Issue by jasonhemann** [magit/ghub#33]
Could you suggest which scope(s) a user should provide for the magit token? And perhaps add these details to the installation instructions?

**Comment by vermiculus** [comment]
> magit token

Did I miss something in magit's development or do you mean a ghub application token?

**Comment by jasonhemann** [comment]
You are correct. I mean the github application token that the [README](https://github.com/magit/ghub/blob/master/README.md) for magit/ghub asks the user to create. 

If someone could suggest settings for that token, assuming I'm just using it for this, that would be helpful. I can imagine someone else wanting those suggested defaults in the README.

**Comment by vermiculus** [comment]
It depends on what you want to do in the application. For example, Magithub will want `repo`, `notifications` and `user` (and possibly more in the future). Suggesting defaults is probably more on the shoulders of consuming applications (like Magithub).

**Comment by jasonhemann** [comment]
Hm. I suppose that's probably so.
