### ISSUE TITLE
"Token not found" error

### ISSUE THREAD

**Issue by kvolkovich-sc** [magit/ghub#36]
I install "magithub" from "Melpa"

It depends on "ghub". When I try to auth, it fails with error "Token not found".  `ghub--auth-source-get` always returns `nil`.

`hub browse`, then input login, pass works correctly.

I solved auth problem by replacing content of **ghub.el** dependency locally to https://raw.githubusercontent.com/magit/ghub/c74101ca6235a20ec428ed223ce060a61db26148/ghub.el.

P.S. Do you know, is there any to set specific dependency version (I am not a pro in emacs) to avoid these types of confusing errors?)

**Comment by vermiculus** [comment]
How are you attempting to authenticate?

**Comment by kvolkovich-sc** [comment]
Just run `hub issue` in terminal or any another `hub` command which requires auth.

`~/.authinfo.gpg` file exists. `~/.config/hub` file with token creates properly.

I tried with two github accounts.

**Comment by tarsius** [comment]
`ghub.el` does not use the `hub` command line tool, so configuring the latter does nothing for the former. The documentation explains how `ghub.el` has to be configured. However I am currently working on a new release which will make this easier.
