### ISSUE TITLE
can't read the token in the authinfo.gpg

### ISSUE THREAD

**Issue by seblemaguer** [magit/ghub#40]
Hello,

I tried to run this command: 

```elisp
(ghub-get "/user")
```
which did several prompted and lead to creation of a key on my github account and to save it in my authinfo.gpg. After verification, I have a line like this one in my authinfo.gpg :

```
machine api.github.com login seblemaguer^ghub password <key>
```

where `<key>` correspond to the key generated by ghub as I can checked on my github account. However, when I rerun the command `ghub-get`, it ignores the key stored in my authinfo. I checked with only this line on the authinfo.gpg, same problem. Do you have a lead on where to have a look?

Thanks a lot

**Comment by vermiculus** [comment]
Can you try the following?

```lisp
(ghub-get "/user" nil :auth 'ghub)
```

/cc @tarsius

**Comment by tarsius** [comment]
@vermiculus I am taking off for two weeks. Happy holidays!

**Comment by seblemaguer** [comment]
Hello,

thanks a lot for the suggestion. I had a syntax problem in my authinfo file. I thought restarted emacs when I tried by cleaning it but that wasn't the case.

Happy holidays and celebrations
