### ISSUE TITLE
Plans for v3

### ISSUE THREAD

**Issue by tarsius** [magit/ghub#46]
*Actually, lets do that all in v2.*

**Comment by vermiculus** [comment]
Re graphql -- do you want me to throw what I have up on MELPA?

**Comment by tarsius** [comment]
Okay, I wasn't expecting for you to respond *that* quickly...

> Re graphql -- do you want me to throw what I have up on MELPA?

I tried that out last night ... and I am skeptical. I think `graphql.el` still needs more work.

Maybe that's just because it was late at night, but I could not translate this trivial query to your dsl:

```
query {
  __schema {
    types {
      name
      kind
      description
      fields {
        name
      }
    }
  }
}
```

I either got an error (probably my fault), or the part `kind ... fields { name }` got discarded by your code (probably a bug). You should probably go through all the examples in the Github and Graphql tutorials and write all the example code using your dsl.

That would help finding bugs and also serve as documentation.

> Support Graphql

I have learned SQL using the dsl provided by `emacsql.el`, which wasn't able to express everything and had some bugs. I don't want to go through the same with GraphQL and instead learn the real thing first.

So far `ghub.el` isn't too opinionated and I want to keep it that way. With regards to `ghub-query` and `ghub-mutatation` that means that it should take a Graphql string as QUERY and MUTATION (but expect a json-like alist as VARIABLES and return a json-like alist). Once more I will leave the opinionated parts for other packages to implement.

So users will have to use `(ghub-query (graphql-encode ...) ...)` or can also just `(ghub-query "query {...}" ...)`.

**Comment by vermiculus** [comment]
I'm still working on a lot of the more advanced GraphQL syntax (like fragments and aliased), but explicit queries should work -- they've worked enough for me to develop some basic real-world queries to GitHub. Check out the examples.el in that directory (or some such file). I've been working off of http://graphql.org/learn/.

Definitely learning GraphQL proper would be prerequisite for using `graphql.el` :-)

`(ghub-query (graphql-encode ...) ...)` looks appropriate to me and is in-line with the spirit of ghub.
