### ISSUE TITLE
How to use SPADES assembler to de novo assembly contigs

### ISSUE THREAD

**Issue by 201314918** [magit/ghub#50]
How to use SPADES assembler to de novo assembly contigs

 I have Contigs that were generated true the SPADES assembler I then used mitochondrial genomes to search for contigs that match with MITOCHONDRIAL GENOME . Now I would like to find out, how can I use the SPADES assembler to join those contigs into scaffolds?. I dont have a feference for my species. I am in need of the command that I need to run in order to do this job.
I am running SPADES 3.11.1
Thank you

**Comment by vermiculus** [comment]
I think you've got the wrong bug tracker.

**Comment by 201314918** [comment]
Hi vermiculus 
Could you please explain. I am new to this kind of work. I have the contigs, then I used BlastN o search for matching contigs, Now I am just stuck on how to get those contigs now rearranged (ordered back consecutively into Mitochonrion)

Thanks

**Comment by tarsius** [comment]
>> I think you've got the wrong bug tracker.

> Could you please explain. I am new to this kind of work. 

Talking about something completely unrelated here won't get you any answers to your question. This is because we don't know what the hell you are talking about.
