### ISSUE TITLE
ghub--auth-source-get uses token for a different :user

### ISSUE THREAD

**Issue by basil-conto** [magit/ghub#60]
I use a [custom `auth-source` backend](https://github.com/basil-conto/dotfiles/blob/master/.emacs.d/lisp/blc-pass.el) for querying the Unix [`pass` utility](https://www.passwordstore.org/) (which I wrote because the now-built-in [`auth-source-pass` backend](http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/auth-source-pass.el) suffers from several bugs/limitations which I have not yet addressed upstream).

One (under-documented) `auth-source` feature which my backend supports is the `:require` search property. Quoth the docstring of `auth-source-search`:

    :require (A B C) means that only results that contain those
    tokens will be returned.  Thus for instance requiring :secret
    will ensure that any results will actually have a :secret
    property.

No callers of `ghub--auth-source-get` currently specify the `:require` property. The effect of this is that Ghub unconditionally uses the first search result, even when I have multiple `api.github.com` tokens that differ only in the `:user` (AIUI, `auth-source-search` searches based on a union of all specified properties when `:require` is omitted; see [`(auth) Help for developers`](https://www.gnu.org/software/emacs/manual/html_node/auth/Help-for-developers.html#Help-for-developers)).

If `ghub--token` specified the `:require` property, then this would disambiguate the multiple `api.github.com` tokens I have. To address this, I currently intercept calls to `ghub--auth-source-get` and add the `:require` property myself using [advice](https://github.com/basil-conto/dotfiles/blob/1414cea1388643cf92b382a6a59029ae7ee449a6/.emacs.d/init.el#L177-L185).

So I think that `ghub--token` should specify the `:require` property, but maybe I'm missing something? WDYT?

**Comment by tarsius** [comment]
Sounds good.

**Comment by basil-conto** [comment]
Closing; see https://github.com/magit/ghub/pull/61#discussion_r193965452.
