### ISSUE TITLE
Question: simple method to get notifications

### ISSUE THREAD

**Issue by seagle0128** [magit/ghub#75]
Hi, I am wondering if there is a simple method to get notifications via `ghub`. Can you please give an example or snippet?

I am using `ghub+` currently, but i'd like remove this dependency since I've switched from `magithub` to `forge`.
```elisp
(ignore-errors
  (ghubp-get-notifications :participating "true"))
```

**Comment by vermiculus** [comment]
Just using ghub would be `(ghub-get "/notifications" :query '((notifications . "true")))`. Forge has its own utility functions (functions starting as `forge--ghub-`) but I think those require special data structures.

**Comment by seagle0128** [comment]
Thanks! But it should be `(ghub-get "/notifications" '((notifications . "true")) :query)`, right?

**Comment by seagle0128** [comment]
Thanks for the update. I've updated my codes accordingly.

**Comment by seagle0128** [comment]
@vermiculus  It seems the snippet doesn't work anymore :( Can you please take a look at this issue again? Thanks!

**Comment by vermiculus** [comment]
@seagle0128 What doesn't work about it? Is there an error? It still works for me if I've got a token with the `notifications` scope.

**Comment by seagle0128** [comment]
@vermiculus The snippet works a gain after I upgrading to Emacs 29.
