### ISSUE TITLE
*-token-scopes

### ISSUE THREAD

**Issue by YoungFrog** [magit/ghub#76]
At
https://magit.vc/manual/ghub/Manually-Creating-and-Storing-a-Token.html#Manually-Creating-and-Storing-a-Token
it is written:

> A package named PACKAGE has to specify the scopes that it wants in the variable named PACKAGE-ghub-token-scopes. The doc-string of such variables should document what the various scopes are needed for. 

I did not find any .*-ghub-token-scopes variables even though I have `forge` installed. But I do see variables of the form `PACKAGE-FORGE-token-scopes`:

> forge-github-token-scopes
>   Variable: The Github API scopes needed by Magit.
>   Properties: variable-documentation
> forge-gitlab-token-scopes
>   Variable: The Gitlab API scopes needed by Magit.
>   Properties: variable-documentation
> ghub-github-token-scopes
>   Variable: The Github API scopes that your private tools need.
>   Properties: variable-documentation

**Comment by YoungFrog** [comment]
@tarsius Shouldn't gitlab be mentionned too ?

**Comment by tarsius** [comment]
Yeah, but this is not the only place in the documentation that has not been updated since `ghub` started supporting other forges beside Github. I'll update all that in one go eventually.
