### ISSUE TITLE
Requerimientos sitio vida con sentido

### ISSUE THREAD

**Issue by evyramirez** [magit/ghub#80]
Hola cielo!

Necesito un inmenso y encarecido favor, bueno, dos:
1. Podemos Cambiar en la portadilla Coach Existencial por Coach Logoterapéutica? cómo te parece que se vería?
2. Incluir al final de las páginas mi cuenta en Pinterest: Vida con Sentido

Gracias!!!!

**Comment by vermiculus** [comment]
Did you open this issue in the correct tracker?

**Comment by evyramirez** [comment]
Sorry about that!
