### ISSUE TITLE
ghub-use-workaround-for-emacs-bug  will break in emacs 25 for gitlab

### ISSUE THREAD

**Issue by yisraeldov** [magit/ghub#89]
@tarsius Hi, so this breaks in emacs 25 using gitlab.
 it causes:
 
```
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname gitlab.com :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
```

This will fix in a config/setup file
``` emacs-lisp
(setq ghub-use-workaround-for-emacs-bug nil)
```

I don't know if this is unique to gitlab or to emacs 25.

**Comment by vermiculus** [comment]
cross-referencing: 311cc99ddde0301eec41835705856b9f15be2111

**Comment by npostavs** [comment]
I think this is not gitlab-specifc, but gnutls version specific. I guess gnutls versions earlier than 3.6 don't recognize "-TLS1.3" so they return an error. @yisraeldov what gnutls version do you have? (Check the value of the Emacs variable `libgnutls-version`)

**Comment by yisraeldov** [comment]
libgnutls-version’s value is 30508

**Comment by davep** [comment]
@tarsius [pointed me here](https://github.com/magit/forge/issues/152#issuecomment-495162363) from an issue [I raised in forge](https://github.com/magit/forge/issues/152). I've just recently started having this issue with both an internal GitLab server, and with GitHub itself. My setup is "GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.30) of 2019-04-15". `libgnutls-version` is 30410.

Just tested the:

```elisp
(setq ghub-use-workaround-for-emacs-bug nil)
```

mentioned above and that has it all working for me.

**Comment by yisraeldov** [comment]
So it seems like maybe that "fix" wasn't a fix, and shouldn't be
enabled by default.

**Comment by npostavs** [comment]
> So it seems like maybe that "fix" wasn't a fix, and shouldn't be enabled by default.

Basically, it should be turned off if your gnutls version is lower than 3.6.3:

<https://lists.gnupg.org/pipermail/gnutls-devel/2018-July/008584.html>:

>    I've just released gnutls 3.6.3. This is the first release which
>    adds full support of TLS1.3...

**Comment by yisraeldov** [comment]
excellent! thanks for the fast response and fix for this.

**Comment by tarsius** [comment]
Thanks @npostavs!

**Comment by vermiculus** [comment]
I've got GnuTLS 3.6.7 and the default behavior fails for me. Confirmed by setting the new var to nil and retying the workflow (which now works).

**Comment by npostavs** [comment]
> I've got GnuTLS 3.6.7 and the default behavior fails for me.

Which Emacs version do you have? What error do you get?

**Comment by vermiculus** [comment]
`GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-28`

```
gnutls.c: [1] (Emacs) connecting to host: api.github.com
gnutls.c: [1] (Emacs) allocating credentials
gnutls.c: [2] (Emacs) allocating x509 credentials
gnutls.c: [2] (Emacs) using default verification flags
gnutls.c: [1] (Emacs) setting the trustfile:  /etc/ssl/cert.pem
gnutls.c: [1] (Emacs) gnutls callbacks
gnutls.c: [1] (Emacs) gnutls_init
gnutls.c: [1] (Emacs) got non-default priority string: NORMAL:-VERS-TLS1.3
gnutls.c: [1] (Emacs) setting the priority string
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname api.github.com :loglevel 2 :min-prime-bits 256 :trustfiles (/etc/ssl/cert.pem) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
```

**Comment by npostavs** [comment]
Hmm, and you're sure the libgnutls version that Emacs is using is 3.6.7? I can't see why it should fail, unless there is some macOS specific weirdness.

**Comment by tarsius** [comment]
@vermiculus Please double check which libgnutls version Emacs is using. (Check the value of the Emacs variable `libgnutls-version`)
