### ISSUE TITLE
Unable to enter 2FA code with leading zero

### ISSUE THREAD

**Issue by vkurup** [magit/ghub#96]
When I tried to use `magit-checkout-pull-request`, I was prompted to create a Github API token, and then for my 2FA token. I received my token, which was a 6 digit number which happened to start with the number `0`. 

`ghub.el` didn't accept the value and in the re-prompt, it showed my token, but without the leading `0` making me think it tried using the token without that zero.

I regenerated another 2FA request and the next code didn't start with zero, and that was successful.

Not 100% sure if this was related to a bug in ghub.el, but wanted to create an issue, in case it was.

**Comment by tarsius** [comment]
This was fixed in #85.
