### ISSUE TITLE
Error installing (via melpa w/r/t forge)

### ISSUE THREAD

**Issue by justinabrahms** [magit/ghub#99]
Hello. I attempted to install forge via `package-install`. This errored in emacs 26.3 due to a missing tar on melpa. 

```
helm-M-x: http://melpa.org/packages/ghub-20191005.1236.tar: Not found
```

Perhaps a release gone bad?

**Comment by tarsius** [comment]
@purcell I forgot, can you somehow trigger another built?

**Comment by purcell** [comment]
I don't have public key access to the build machine any more, I think since @milkypostman last changed the setup - perhaps he can add it back pls? `curl https://github.com/purcell.keys | head -1 >> ~/.ssh/authorized_keys`.

**Comment by milkypostman** [comment]
Ok will take a look at this later tonight. Sorry for the delay.

**Comment by milkypostman** [comment]
this is fixed

**Comment by tarsius** [comment]
Thanks!
